# File is used by the openapi-generator cli to generate a test client for unit tests.
generatorName: go
inputSpec: /local/openapi/v1/spec.yaml
outputDir: /local/internal/testing/openapi/v1/testclient
packageName: testclient